[package]
name = "polkadot-node-core-proposer"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.4"
log = "0.4.8"
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-overseer = { path = "../../overseer" }
polkadot-primitives = { path = "../../../primitives" }
sc-basic-authorship = { git = "https://github.com/mxinden/substrate", branch = "buggy-code" }
sc-block-builder = { git = "https://github.com/mxinden/substrate", branch = "buggy-code" }
sc-client-api = { git = "https://github.com/mxinden/substrate", branch = "buggy-code" }
sp-api = { git = "https://github.com/mxinden/substrate", branch = "buggy-code" }
sp-blockchain = { git = "https://github.com/mxinden/substrate", branch = "buggy-code" }
sp-consensus = { git = "https://github.com/mxinden/substrate", branch = "buggy-code" }
sp-core = { git = "https://github.com/mxinden/substrate", branch = "buggy-code" }
sp-inherents = { git = "https://github.com/mxinden/substrate", branch = "buggy-code" }
sp-runtime = { git = "https://github.com/mxinden/substrate", branch = "buggy-code" }
sp-transaction-pool = { git = "https://github.com/mxinden/substrate", branch = "buggy-code" }
wasm-timer = "0.2.4"
